apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  labels:
    app: backend
  name: backend
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: backend
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - image: xxxxxxxxxxxxxxxxxxxxxxx/workshop/backend
        imagePullPolicy: Always
        name: backend
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        ports:
          - name: backend-http
            containerPort: 8080
        env:
        - name: "AUTH"
          value: "workshop-auth"
        - name: "BROKER_URL"
          value: "tcp://broker:3000"
        - name: "PORT"
          value: "8080"
        - name: "SUBSCRIBE_TOPIC"
          value: "mqtt-k8s-workshop"
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30

